### ISSUE TITLE
about the safety of ServerSeeker V2

### ISSUE THREAD

**Issue by PKU-SESS-MCserver** [Funtimes909/ServerSeekerV2-Discord-Bot#3]
My server was detected by ServerSeeker V2 several days ago and some foreign players went into the server. I would like to know how to avoid being detected, because the server is actually a PC and is only for private usage. Does it help if I set the access permission?

Thank you

**Comment by EngurRuzgar** [comment]
Hi, if your server is not cracked, just using a whitelist should suffice. If it is cracked, I would recommend a login plugin along with a whitelist. If you don't want your server to be tracked by ServerSeekerV2, join our Discord and DM Nucc or Funtimes909. https://discord.gg/nQRjyGef

**Comment by PKU-SESS-MCserver** [comment]
Thanks
